HH_PJ/HH_PJ/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user_APP.urls')),
    path('',include('main_APP.urls')),
]

HH_PJ/main_APP/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.start_page, name='start_page'),
    path('vacancies/', views.vacancy_list_view, name='vacancy_list'),
    path('vacancies/<int:pk>/', views.vacancy_detail_view, name='vacancy_detail'),
    path('vacancies/create/', views.vacancy_create_view, name='vacancy_create'),
    path('vacancies/<int:pk>/update/', views.vacancy_update_view, name='vacancy_update'),
    path('vacancies/<int:pk>/delete/', views.vacancy_delete_view, name='vacancy_delete'),
    # path('vacancies/search/', views.vacancy_list, name='vacancy_filter'),
    path('resumes/', views.resume_list_view, name='resume_list'),
    path('resumes/<int:pk>/', views.resume_detail_view, name='resume_detail'),
    path('resumes/create/', views.resume_create_view, name='resume_create'),
    path('resumes/<int:pk>/update/', views.resume_update_view, name='resume_update'),
    path('resumes/<int:pk>/delete/', views.resume_delete_view, name='resume_delete'),
]

HH_PJ/main_APP/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models



class Skills(models.Model):
    name = models.CharField(
        max_length=100
    )

    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(
        max_length=100
    )
    description = models.TextField()
    address = models.CharField(
        max_length=100
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.name





class Vacancy(models.Model):
    title = models.CharField(
        max_length=100
    )
    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name='vacancies'
    )
    salary = models.IntegerField()
    skills = models.ManyToManyField(
        Skills,
        related_name='vacancy_skills'
    )
    description = models.TextField()
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    job_types = [
        ('FULL_TIME', 'Полная занятость'),
        ('PART_TIME', 'Частичная занятость'),
        ('REMOTE', 'Удаленная работа'),
    ]
    type_of_job = models.CharField(
        max_length=100,
        choices=job_types
    )

    def __str__(self):
        return self.title





class Resume(models.Model):
    dream_job = models.CharField(
        max_length=100
    )
    name = models.CharField(
        max_length=100
    )
    surname = models.CharField(
        max_length=100
    )
    lastname = models.CharField(
        max_length=100
    )
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=16)
    skills = models.ManyToManyField(
        Skills,
        related_name='resume_skills'
    )
    exp = models.CharField(
        max_length=100
    )
    education_type = [
        ('SCHOOL', 'Школьное'),
        ('BAKALAVR', 'Бакалавр'),
        ('PROFESSOR', 'Профессор'),
        ('MAGISTR_DJEDAY', 'Джедай'),
    ]
    education = models.CharField(
        max_length=100,
        choices=education_type
    )
    gender_type = [
        ('MALE', 'Муж.'),
        ("FEMALE", "Жен."),
        ("ЕГОРФАНЫ", "Шухназар"),
        ("DOB", "Асад"),
        ('SCHOOL', 'Школьное'),
        ("LAMINAT", 'Ламинат'),
        ("MAYONEZ", 'Майонез'),
        ("KETCHUP", 'Кетчуп'),
        ("KETCHUNEZ", 'Кетчунез'),
        ("OTHER", 'Другое'),
    ]
    gender = models.CharField(
        max_length=100,
        choices=gender_type
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='resumes'
    )

    def __str__(self):
        return self.name


class Request(models.Model):
    vacancy = models.ForeignKey(
        Vacancy,
        on_delete=models.CASCADE,
        related_name='request'
    )
    resume = models.ForeignKey(
        Resume,
        on_delete=models.CASCADE,
        related_name='request'
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    status_type = [
        ('NEW', 'Новый'),
        ('ACCEPT', 'Принят'),
        ('RE_CALL', 'Перезвонят')
    ]
    status = models.CharField(
        max_length=100,
        choices=status_type
    )


HH_PJ/main_APP/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Resume, Vacancy, Company

class ResumeCreateForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['dream_job', 'name', 'surname', 'lastname', 'date_of_birth', 'email', 'phone', 'skills', 'exp', 'education', 'gender']

class ResumeUpdateForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['dream_job', 'name', 'surname', 'lastname', 'date_of_birth', 'email', 'phone', 'skills', 'exp', 'education', 'gender']

class VacancyCreateForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = ['title', 'company', 'salary', 'skills', 'description', 'type_of_job']

class VacancyUpdateForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = ['title', 'company', 'salary', 'skills', 'description', 'type_of_job']

class CompanyCreateForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'description', 'address']

class VacancyFilterForm(forms.Form):
    employer = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=True), required=False, label='Работодатель')

HH_PJ/main_APP/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from main_APP.forms import VacancyUpdateForm, VacancyCreateForm, ResumeUpdateForm, ResumeCreateForm, VacancyFilterForm
from main_APP.models import Vacancy, Resume


# Create your views here.

def start_page(request):
    return render(request, 'main_APP/start_page.html',context={'user': request.user})

@login_required(login_url='login_page')
def vacancy_list_view(request):
    vacancies = Vacancy.objects.all()
    return render(request, 'main_APP/vacancy_list.html', {'vacancies': vacancies})


@login_required(login_url='login_page')
def vacancy_detail_view(request, pk):
    vacancy = get_object_or_404(Vacancy, pk=pk)
    return render(request, 'main_APP/vacancy_detail.html', {'vacancy': vacancy})


@login_required(login_url='login_page')
def resume_list_view(request):
    resumes = Resume.objects.all()
    return render(request, 'main_APP/resume_list.html', {'resumes': resumes})


@login_required(login_url='login_page')
def resume_detail_view(request, pk):
    resume = get_object_or_404(Resume, pk=pk)
    return render(request, 'main_APP/resume_detail.html', {'resume': resume})


@login_required(login_url='login_page')
def resume_create_view(request):
    if request.method == 'POST':
        form = ResumeCreateForm(request.POST)
        if form.is_valid():
            resume = form.save(commit=False)
            resume.user = request.user
            resume.save()
            return redirect('resume_list')
    else:
        form = ResumeCreateForm()
    return render(request, 'main_APP/resume_create.html', {'form': form})


@login_required(login_url='login_page')
def resume_update_view(request, pk):
    resume = get_object_or_404(Resume, pk=pk)
    if request.method == 'POST':
        form = ResumeUpdateForm(request.POST, instance=resume)
        if form.is_valid():
            form.save()
            return redirect('resume_list')
    else:
        form = ResumeUpdateForm(instance=resume)
    return render(request, 'main_APP/resume_update.html', {'form': form})


@login_required(login_url='login_page')
def resume_delete_view(request, pk):
    resume = get_object_or_404(Resume, pk=pk)
    resume.delete()
    return redirect('resume_list')


@login_required(login_url='login_page')
@staff_member_required(login_url='')
def vacancy_create_view(request):
    if request.method == 'POST':
        form = VacancyCreateForm(request.POST)
        if form.is_valid():
            vacancy = form.save(commit=False)
            vacancy.user = request.user
            vacancy.save()
            return redirect('vacancy_list')
    else:
        form = VacancyCreateForm()
    return render(request, 'main_APP/vacancy_create.html', {'form': form})


@login_required(login_url='login_page')
@staff_member_required
def vacancy_update_view(request, pk):
    vacancy = get_object_or_404(Vacancy, pk=pk)
    if request.method == 'POST':
        form = VacancyUpdateForm(request.POST, instance=vacancy)
        if form.is_valid():
            form.save()
            return redirect('vacancy_list')
    else:
        form = VacancyUpdateForm(instance=vacancy)
    return render(request, 'main_APP/vacancy_update.html', {'form': form})


@login_required(login_url='login_page')
@staff_member_required
def vacancy_delete_view(request, pk):
    vacancy = get_object_or_404(Vacancy, pk=pk)
    vacancy.delete()
    return redirect('vacancy_list')


# @login_required(login_url='login_page')
# @staff_member_required
# def vacancy_list(request,pk):
#     form = VacancyFilterForm(request.GET)
#     vacancies = Vacancy.objects.all()
#
#     if form.is_valid():
#         employer = form.cleaned_data.get('employer')
#         if employer:
#             vacancies = vacancies.filter(employer=employer)
#
#     context = {
#         'form': form,
#         'vacancies': vacancies
#     }
#     return render(request, 'main_APP/vacansy_list_staff.html', context)

HH_PJ/main_APP/templates/main_APP/resume_create.html
{% extends 'main_APP/layouts/base.html' %}
{% block content %}
<h1>Create Resume</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

HH_PJ/main_APP/templates/main_APP/resume_detail.html
{% extends 'main_APP/layouts/base.html' %}

{% block content %}
<h1>{{ resume.dream_job }}</h1>
<p><strong>Name:</strong> {{ resume.name }}</p>
<p><strong>Surname:</strong> {{ resume.surname }}</p>
<p><strong>Lastname:</strong> {{ resume.lastname }}</p>
<p><strong>Date of Birth:</strong> {{ resume.date_of_birth }}</p>
<p><strong>Email:</strong> {{ resume.email }}</p>
<p><strong>Phone:</strong> {{ resume.phone }}</p>
<p><strong>Skills:</strong> {{ resume.skills.all|join:", " }}</p>
<p><strong>Experience:</strong> {{ resume.exp }}</p>
<p><strong>Education:</strong> {{ resume.get_education_display }}</p>
<p><strong>Gender:</strong> {{ resume.get_gender_display }}</p>
{% endblock %}

HH_PJ/main_APP/templates/main_APP/resume_list.html
{% extends 'main_APP/layouts/base.html' %}

{% block content %}
<h1>Resume List</h1>
<ul>
    {% for resume in resumes %}
        <li><a href="{% url 'resume_detail' resume.pk %}">{{ resume.dream_job }}</a></li>
    {% empty %}
        <form action="{% url 'resume_create' %}">
            <li>There's no any resume. If you'd like to create one, press <button style="margin-right: 300px">here</button></li>
        </form>
    {% endfor %}
</ul>
{% endblock %}

HH_PJ/main_APP/templates/main_APP/resume_update.html
{% extends 'main_APP/layouts/base.html' %}
{% block content %}
<h1>Update Resume</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

HH_PJ/main_APP/templates/main_APP/start_page.html
{% extends 'main_APP/layouts/base.html' %}

{% block content %}
<div class="card">
    <h2>Welcome to the HH COPY!!!!!</h2>
    <p>Типо HeadHunter</p>
    {% if not user.is_authenticated %}
        <p>If you don't have an account, you can <a href="{% url 'register_page' %}">sign up here</a>.</p>
    {% endif %}
</div>
{% endblock %}

HH_PJ/main_APP/templates/main_APP/vacancy_create.html
{% extends 'main_APP/layouts/base.html' %}
{% block content %}
<h1>Create Vacancy</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

HH_PJ/main_APP/templates/main_APP/vacancy_detail.html
{% extends 'main_APP/layouts/base.html' %}
{% block content %}
<h1>{{ vacancy.title }}</h1>
<p><strong>Company:</strong> {{ vacancy.company.name }}</p>
<p><strong>Salary:</strong> {{ vacancy.salary }}</p>
<p><strong>Required Skills:</strong> {{ vacancy.skills.all|join:", " }}</p>
<p><strong>Description:</strong> {{ vacancy.description }}</p>
<p><strong>Type of Job:</strong> {{ vacancy.get_type_of_job_display }}</p>
    <a href="{% url 'vacancy_list' %}"><button>Back to Vacancy List</button></a>
    <a href=""><button onclick="get_alert()">Send a Resume</button></a>
{% if user.is_staff %}
    <a href="{% url 'vacancy_update' vacancy.pk %}">Edit</a>
    <a href="{% url 'vacancy_delete' vacancy.pk %}">Delete</a>
{% endif %}
{% endblock %}

HH_PJ/main_APP/templates/main_APP/vacancy_list.html
{% extends 'main_APP/layouts/base.html' %}
{% block content %}
<h1>Vacancy List</h1>
<ul>
    {% for vacancy in vacancies %}
        <li>
            <a href="{% url 'vacancy_detail' vacancy.pk %}">{{ vacancy.title }}</a>
            {% if user.is_staff %}
                <a href="{% url 'vacancy_update' vacancy.pk %}"><button>Edit</button></a>
                <a href="{% url 'vacancy_delete' vacancy.pk %}"><button>Delete</button></a>
                <a href="#"><button>Filter Vacancy (Not working)</button></a>
            {% endif %}
        </li>
    {% empty %}
        <li>There's no any vacancy. Please wait until something appear!</li>
        {% if request.user.is_staff %}
           <form action="{% url 'vacancy_create' %}">
            <h2>Staff members warning!</h2>
            <li>There's no any resume. If you'd like to create one, press <button style="margin-right: 300px">here</button></li>
        </form>
        {% endif %}
    {% endfor %}
</ul>
{% endblock %}

HH_PJ/main_APP/templates/main_APP/vacansy_list_staff.html
{% extends 'main_APP/layouts/base.html' %}

{% block title %}Vacancies{% endblock %}

{% block content %}
<h1>Vacancies</h1>

<form method="get">
    {{ form.as_p }}
    <button type="submit">Filter</button>
</form>

<ul>
    {% for vacancy in vacancies %}
        <li>{{ vacancy.title }} - {{ vacancy.employer.username }}</li>
        {% empty %}
        <p>There are no active vacancies at the moment.</p>
    {% endfor %}
</ul>


{% endblock %}